import { StyleSheet } from "react-native";

export const globalStyles = StyleSheet.create({
  container: {
    flex: 1,
    marginLeft: 2,
    marginRight: 2,
    marginBottom: 20,
    backgroundColor: "#fff",
    alignItems: "center",
  },
  buttonContainer: {
    flexDirection: "row",
    justifyContent: "space-evenly",
    alignItems: "center",
    marginTop: 5,
    paddingTop: 5,
    paddingBottom: 5,
    backgroundColor: "#fff",
  },
  ques: {
    justifyContent: "center",
    textAlign: "center",
    fontSize: 16,
    marginLeft: 25,
    marginRight: 25,
    color: "#4b788f",
    lineHeight: 23,
    fontFamily: "OpenSans-Regular",
  },
  text1: {
    justifyContent: "center",
    textAlign: "center",
    fontSize: 16,
    marginTop: 25,
    marginLeft: 25,
    marginRight: 25,
    marginBottom: 25,
    backgroundColor: "#fff",
    lineHeight: 23,
    fontFamily: "OpenSans-Light",
  },
  text2: {
    justifyContent: "center",
    textAlign: "center",
    fontSize: 16,
    marginTop: 5,
    marginLeft: 25,
    marginRight: 25,
    backgroundColor: "#fff",
    lineHeight: 23,
    fontFamily: "OpenSans-Light",
  },
  text3: {
    justifyContent: "center",
    textAlign: "center",
    fontSize: 16,
    marginTop: 5,
    backgroundColor: "#fff",
    color: "#EF8354",
    lineHeight: 23,
    fontFamily: "OpenSans-Regular",
  },
  buttonContainer2: {
    flexDirection: "row",
    justifyContent: "flex-end",
    alignItems: "center",
    marginLeft: 5,
    marginRight: 5,
    marginTop: 5,
    paddingTop: 5,
    marginBottom: 15,
    paddingBottom: 5,
    backgroundColor: "#fff",
  },
  signup1: {
    fontSize: 16,
    paddingLeft: 5,
    paddingBottom: 5,
    justifyContent: "space-evenly",
    color: "#292929",
    fontFamily: "OpenSans-Light",
    // fontWeight: "bold",
  },
});
