import { StyleSheet } from "react-native";

export const globalStyles = StyleSheet.create({
  container: {
    flex: 1,
    marginLeft: 2,
    marginRight: 2,
    marginBottom: 15,
    backgroundColor: "#fff",
    alignItems: "center",
  },
  container2: {
    flex: 1,
    marginLeft: 2,
    marginRight: 2,
    marginBottom: 20,
    marginTop: 20,
    backgroundColor: "#fff",
    alignItems: "center",
    borderWidth: 0.8,
    borderColor: "grey",
    borderRadius: 2,
  },
  buttonContainer: {
    flexDirection: "row",
    justifyContent: "space-evenly",
    alignItems: "center",
    marginTop: 5,
    paddingTop: 5,
    paddingBottom: 5,
    backgroundColor: "#fff",
  },
  ques: {
    justifyContent: "center",
    textAlign: "center",
    fontSize: 16,
    marginLeft: 25,
    marginRight: 25,
    color: "#4b788f",
    lineHeight: 23,
    fontFamily: "OpenSans-Regular",
  },
  text1: {
    justifyContent: "center",
    textAlign: "center",
    fontSize: 16,
    marginTop: 25,
    marginLeft: 25,
    marginRight: 25,
    marginBottom: 25,
    backgroundColor: "#fff",
    lineHeight: 23,
    fontFamily: "OpenSans-Light",
  },
  text2: {
    justifyContent: "center",
    textAlign: "center",
    fontSize: 16,
    marginTop: 5,
    marginLeft: 25,
    marginRight: 25,
    backgroundColor: "#fff",
    lineHeight: 23,
    fontFamily: "OpenSans-Light",
  },
  text3: {
    justifyContent: "center",
    textAlign: "center",
    fontSize: 16,
    marginTop: 5,
    backgroundColor: "#fff",
    color: "#EF8354",
    lineHeight: 23,
    fontFamily: "OpenSans-Regular",
  },
  buttonContainer2: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    marginLeft: 5,
    marginRight: 5,
    marginTop: 5,
    paddingTop: 5,
    marginBottom: 10,
    paddingBottom: 5,
    backgroundColor: "#fff",
  },
  signup1: {
    fontSize: 16,
    paddingLeft: 5,
    paddingBottom: 5,
    justifyContent: "space-evenly",
    color: "#292929",
    fontFamily: "OpenSans-Light",

    // fontWeight: "bold",
  },
  fields: {
    paddingBottom: 0,
  },
  errorText: {
    color: "crimson",
    fontWeight: "bold",
    marginBottom: 10,
    marginTop: 6,
    textAlign: "center",
  },
  title: {
    textAlign: "center",
    fontSize: 16,
    color: "#fff",
    fontWeight: "bold",
    fontFamily: "OpenSans-Light",
  },
  input: {
    borderWidth: 1,
    borderColor: "#ddd",
    padding: 10,
    fontSize: 18,
    borderRadius: 6,
    flexDirection: "row",
    backgroundColor: "#C8DCEF",
  },
  picker: {
    // fontSize: 12,
    // backgroundColor: "#C8DCEF",
    transform: [{ scaleX: 0.9 }, { scaleY: 0.9 }],
  },
});
